language: php

sudo: false

php:
  - 7.0

before_script:
  - pecl channel-update pecl.php.net
  - echo "no" | pecl install apcu
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install -n
script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.0' ]; then php vendor/bin/coveralls; fi

after_success:
  - travis_retry php vendor/bin/coveralls -v